### ISSUE TITLE
`Lint/Syntax` failures seem unavoidable

### ISSUE THREAD

**Issue by sato11** [r7kamura/rubocop-slim#26]
I have observed a couple of `Lint/Syntax` failures in an attempt to get this plugin onboard. 

Perhaps 9dd2c1e0d0be8417ce90b44161a4a006cdbb7055 was confused and the intention was to list `Lint/Syntax`? I'm not 100% sure but replacing `Lint/SyntaxError` with `Lint/Syntax` seems to get things to work. 

There seems to be not many options for us basic users to do to work around, since it is basically prohibited to tweak the rule regarding `Lint/Syntax` unless by extending the default.[^1] So it would be great it you can take a glance to help us move on. 

Thanks in advance!

[^1]: https://github.com/rubocop/rubocop/blob/v1.66.1/lib/rubocop/config_validator.rb#L157

**Comment by r7kamura** [comment]
As you pointed out, this needs to be changed to `Lint/Syntax` 👍

**Comment by r7kamura** [comment]
Thank you @sato11, just released v0.2.8:

- https://github.com/r7kamura/rubocop-slim/releases/tag/v0.2.8
- https://rubygems.org/gems/rubocop-slim/versions/0.2.8

See if this fixes your problem.

**Comment by sato11** [comment]
How legendary it is to catch, fix and release it within 20 minutes 😲 A great respect to the unprecedented level of support. Thank you for the hard work! 👏
